export { Parallelepiped } from './figures/parallelepiped'
export { Cube } from './figures/cube'
export { Cone } from './figures/cone'
export { Cylinder } from './figures/cylinder'
export { Pyramid } from './figures/pyramid'
export { FiguresList } from './figures-list'
